# Intro 1: Linear states and operators

Material adapted from https://github.com/amcdawes/QMlabs. I also recommend
https://github.com/jrjohansson/scientific-python-lectures for a much more general approach to Pyhton

### Part I: vectors in linear spaces

Python has several tools to handle linear states. The functions belong to numpy and scipy libraries. In order to use them, we must load them before calling them. Usually, we include a few lines at the beginning of the code or the notebook


In [10]:
#from numpy import array, dot, outer, sqrt, matrix, trace
#from numpy.linalg import eig, eigvals

import numpy as np
import numpy.linalg as linalg #Sublibreria de numpy para diagonalizar


Vectors are defined as arrays. Row vectors are introduced as a single array, column vectors as an array of 1-arrays

In [11]:
rv = np.array([1.0,2, 3])  # a row 3-vector Row of colums
rv

array([1., 2., 3.])

In [12]:
cv = np.array([[3],[4],[5]])  # a column 3-vector Colum of rows
cv

array([[3],
       [4],
       [5]])

In [13]:
A=np.array([[1,2,3],[2,4,5],[1,1,1]]) #Row made of rows

In [14]:
A

array([[1, 2, 3],
       [2, 4, 5],
       [1, 1, 1]])

We can operate with vectors, using scalar (dot) or vector (outer) products. Remember that they are not commutative!!

In [15]:
np.dot(rv,cv) #PRODUCTO ESCALAR (Row)(Colum)

array([26.])

In [16]:
rv@cv

array([26.])

In [17]:
np.dot(cv,rv) #np.dot NO (Colum)(Row) 

ValueError: shapes (3,1) and (3,) not aligned: 1 (dim 1) != 3 (dim 0)

In [18]:
np.dot(A,cv) #Matrix(Colum)

array([[26],
       [47],
       [12]])

In [19]:
A@cv

array([[26],
       [47],
       [12]])

In [20]:
np.outer(rv,cv) #Estern product (Colum)(Row)=matrix

array([[ 3.,  4.,  5.],
       [ 6.,  8., 10.],
       [ 9., 12., 15.]])

In [21]:
np.outer(cv,rv)

array([[ 3.,  6.,  9.],
       [ 4.,  8., 12.],
       [ 5., 10., 15.]])

### Part II: Complex numbers

Imaginary unit in Python is represented by a j. 

In [22]:
α=2+1j

In [23]:
α

(2+1j)

In [24]:
v1 = np.array([1+2j, 3+2j, 5+1j, 4])
v1

array([1.+2.j, 3.+2.j, 5.+1.j, 4.+0.j])

A complex object admits some operations made on it. Thus, we can define its conjugate as
v1.conjugate()

In [25]:
v1.conjugate()

array([1.-2.j, 3.-2.j, 5.-1.j, 4.-0.j])

We can combine the vector operations and the complex operations:

In [26]:
np.dot(v1,v1) #Escalar porduct

(42+26j)

In [27]:
np.vdot(v1,v1) #Hermitian product 

(60+0j)

### Part III: higher dimensional arrays

Matrices and higher dimensional arrays can be introduced, as "arrays of arrays":

In [28]:
# a two-dimensional array
m1 = np.array([[2,1],[2,1]]) #2x2
m1

array([[2, 1],
       [2, 1]])

In [29]:
# a three-dimensional array (a "cubic hypermatrix")
m2 = np.array([[[2,1],[2,1]], [[3,2],[3,2]]]) #hypercubic matrix matriz de matrices
m2 

array([[[2, 1],
        [2, 1]],

       [[3, 2],
        [3, 2]]])

In [69]:
m2[1,1,1] #El primer indice, accede a la matriz que sea, los otros dos nos dan la posicion de la variable en esa matriz

2

Arrays can be defined implicitly with loops and conditional statements. In this type of commands it is important to remember how indices represent objects in lists.

In [31]:
list=[k for k in range(10)]
list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
len(list)

10

In [33]:
[k@k for k in m2] #lista: k=0-->entrada 0 del array m2 (primera matriz), la multiplica por si misma. Eso forma el primer elemento de la nueva lista

[array([[6, 3],
        [6, 3]]),
 array([[15, 10],
        [15, 10]])]

### Part IV: Operations on matrices

Numpy offers functions to operate on matrices, implementing the most common algebraic tools

A)Hermitian conjugate or transpose are obtained with the  T  or conjugate() suffix

In [34]:
m1.T

array([[2, 2],
       [1, 1]])

In [35]:
m3=np.array([[2j, 1-1j],[2+4j, 3]])
m3

array([[0.+2.j, 1.-1.j],
       [2.+4.j, 3.+0.j]])

In [36]:
m3.T

array([[0.+2.j, 2.+4.j],
       [1.-1.j, 3.+0.j]])

In [37]:
m3.conjugate()

array([[0.-2.j, 1.+1.j],
       [2.-4.j, 3.-0.j]])

In [38]:
(m3.T).conjugate() #Hermitica (Cuidado con los parentesis)

array([[0.-2.j, 2.-4.j],
       [1.+1.j, 3.-0.j]])

Notice that some of these commands depend on the type of object you act on

In [70]:
np.matrix(m3).H #El modificador H (conjugacion hermitica) solo funciona para np.matrix()

matrix([[0.-2.j, 2.-4.j],
        [1.+1.j, 3.-0.j]])

B) Eigenvectors and eigenvalues: are obtained using the "eig" command. The output is common with other math software, such as octave

In [72]:
linalg.eig(m1) #Diagonaliza

(array([3., 0.]),
 array([[ 0.70710678, -0.4472136 ],
        [ 0.70710678,  0.89442719]]))

In [41]:
evals, evecs =linalg.eig(m3) #evals-->autovalores, #evec-->autovectores

In [42]:
evals

array([-1.198948+1.18525737j,  4.198948+0.81474263j])

In [43]:
evecs

array([[-0.13087644+0.68594735j,  0.2690619 -0.15060148j],
       [ 0.71578459+0.j        ,  0.9512754 +0.j        ]])

In [44]:
evecs[:,0] #Fija la fila y coge la coluna n y [i,:] viceversa

array([-0.13087644+0.68594735j,  0.71578459+0.j        ])

In [45]:
evecs[:,1]

array([0.2690619-0.15060148j, 0.9512754+0.j        ])

These arrays can be indexed directly because of the vectoriality. This makes the code simple and easy to read

In [73]:
for k in m2: #m2 lista de dos matrices
    print(linalg.eig(k)) #imprime los atovalores y autovectores de cada matriz

(array([3., 0.]), array([[ 0.70710678, -0.4472136 ],
       [ 0.70710678,  0.89442719]]))
(array([5., 0.]), array([[ 0.70710678, -0.5547002 ],
       [ 0.70710678,  0.83205029]]))


In [47]:
Trace_m2=[np.trace(k) for k in m2] #lista de trazas de las dos matrices

In [48]:
Trace_m2

[3, 5]

# Using Qutip
We can reproduce the tools above inside the qutip-library. States are specified as bra's or ket's, following Dirac notation, and there exists an operation to dualize $|\psi\rangle\to \langle \psi|$. States (kets) are considered to be column vectors, and co-states (bras), row vectors. 

Vamos a ver como hace todo esto QUTIP.

In [79]:
from qutip import *

In [80]:
# Create a row vector:
qv2 = Qobj([[1],[2j]]) #Toma una lista y lo tranforma en un vector cuántico (ket o bra)
qv2 

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.+0.j]
 [0.+2.j]]

In [81]:
qv3=Qobj([[1,2j]]) #Depende de como lo definimos será un ket o un bra
qv3

Quantum object: dims = [[1], [2]], shape = (1, 2), type = bra
Qobj data =
[[1.+0.j 0.+2.j]]

In [82]:
qv2.dag() #cambia de ket a bra o ket

Quantum object: dims = [[1], [2]], shape = (1, 2), type = bra
Qobj data =
[[1.+0.j 0.-2.j]]

### Vector products in QuTiP
Only need to know one operator: "\*"
The product will depend on the order, either inner or outer. Qutip can detect that automatically
$$
|\psi\rangle \langle \psi|
$$

In [83]:
qM=(qv2*qv2.dag()) #proyector
qM

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1.+0.j 0.-2.j]
 [0.+2.j 4.+0.j]]

In [84]:
qv2.dag()*qv2 #numero

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[5.]]

In [54]:
qM

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1.+0.j 0.-2.j]
 [0.+2.j 4.+0.j]]

### Eigenvectors and eigenvalues have their own instructions

In [55]:
qM.eigenenergies() #Autovalores

array([0., 5.])

In [85]:
qM.eigenstates()

(array([0., 5.]),
 array([Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
        Qobj data =
        [[-0.89442719+0.j       ]
         [ 0.        +0.4472136j]]                                   ,
        Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
        Qobj data =
        [[-0.4472136+0.j        ]
         [ 0.       -0.89442719j]]                                   ],
       dtype=object))

In [57]:
qM.eigenstates()[0] #primer obj lusta de autovalres

array([0., 5.])

In [58]:
qM.eigenstates()[1] #lista de vectores propios

array([Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
       Qobj data =
       [[-0.89442719+0.j       ]
        [ 0.        +0.4472136j]]                                   ,
       Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
       Qobj data =
       [[-0.4472136+0.j        ]
        [ 0.       -0.89442719j]]                                   ],
      dtype=object)

In [86]:
qM.eigenstates()[1][0] #de la lista de los autovalores escogemos el que queramos

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[-0.89442719+0.j       ]
 [ 0.        +0.4472136j]]

In [88]:
from qutip.ipynbtools import version_table

version_table()